### ISSUE TITLE
How to access node in browser

### ISSUE THREAD

**Issue by movsky** [johnpapa/docker-angular-cli#3]
I used your image to setup my docker/node/angular-cli application and all works good so far. The container is up and running and my modules are installed.

But how do I access the node-server in my browser? I tried localhost:4200, 127.0.0.1:4200 and even the IP I got from docker inspect. All didn't work. Did i miss to configure something?

This is the party of my docker-compose.yml:

```
frontend:
    image: johnpapa/angular-cli
    container_name: frontend
    command: sh /srv/scripts/npm-init.sh
    working_dir: /usr/app
    volumes:
      - /home/USER/dev/angular-frontend/frontend-app:/usr/app
      - /usr/app/node_modules
      - /home/USER/dev/epubli-ansible/container/frontend/scripts/npm-init.sh:/srv/scripts/npm-init.sh
    ports:
      - "4200:4200"
```
